### ISSUE TITLE
你的这个升级数据库怎么升级？

### ISSUE THREAD

**Issue by gegeName** [xiaolei123/RoomLite#1]
数据库是怎么升级的，是不是直接在继承RoomLiteDatabase的类中方法version中直接把数字调高就行，还是说升级中还要在onUpgrade方法中做操作？如果是这样子的话感觉和room没有多大区别。

**Comment by xiaolei123** [comment]
升级方式目前是在onUpgrade里升级，后期会使用更加简单的方式进行升级

**Comment by gegeName** [comment]
行吗，升级时候能解决数据迁移和更加简单方式那么更好。room升级方式就很繁琐每次升级都要去写SQL语句

**Comment by xiaolei123** [comment]
数据库升级现在可以使用简单的方式进行
