### ISSUE TITLE
kotlin中直接导入依赖创建dao和database后运行报错

### ISSUE THREAD

**Issue by gegeName** [xiaolei123/RoomLite#2]
什么都没调用的情况只创建dao  database 和实体类后运行报错如下错误
[
![image](https://user-images.githubusercontent.com/20966610/123033459-5ed22280-d41a-11eb-85ab-c2d9fc4155a7.png)
](url)

**Comment by xiaolei123** [comment]
检查一下你的gradle配置文件，是否配置了，kotlin-kapt，

dependencies {
    kapt 'com.github.xiaolei123.RoomLite:compiler:0.1.3'
    implementation 'com.github.xiaolei123.RoomLite:runtime:0.1.3'
}

有截图的话就更方便分析一点

**Comment by gegeName** [comment]
已经找到问题了，我后面看了一下，是缺少`def room_version = "2.2.6"
 implementation "androidx.room:room-runtime:$room_version"`  为什么你的框架会有引用room的东西？

**Comment by xiaolei123** [comment]
其实不是Room的东西，是androidx.sqlite，你可以尝试添加
implementation 'androidx.sqlite:sqlite-framework:2.1.0'
implementation 'androidx.sqlite:sqlite:2.1.0'
在你的项目里。

或者检查一下你的gradle是否添加了去掉 androidx.sqlite的 配置。
